version: "3"

services:
  db:
      container_name: database
      environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_DB=sdb
      build: ./sql-setup
      ports:
        - "5432:5432"
      volumes:
        - ./sql-setup:/home/
  space-app:
      build: ./python-setup/
      container_name: SolutionNet
      depends_on:
        - "db"
      command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python spacechem.py'
      depends_on:
        - db
      ports:
      - "80:5000"
      volumes:
        - ./:/app/